export const wrapper: string;
export const transitionForwardEnter: string;
export const transitionBackEnter: string;
export const transitionForwardEnterActive: string;
export const transitionBackEnterActive: string;
export const transitionForwardExit: string;
export const transitionBackExit: string;
export const transitionForwardExitActive: string;
export const transitionBackExitActive: string;
