export const loader: string;
export const load8: string;
export const container: string;
export const image: string;
export const loaded: string;
export const noimage: string;
export const large: string;
export const medium: string;
export const small: string;
